method_list: [
              viloca_ewm,
              viloca_ewm_uni,
              lofreq_local_haplo
              ]
replicate_count: 5
haplotype_generation: mutation_rate
params_path: config_indels/params.csv
master_seq_path: ../../../../hiv/HXB2.fasta
