method_list: [lofreq_local_haplo,
              shorah_default,
              cliquesnv_local_haplo,
              cliquesnv_local_haplo_snv,
              cliquesnv_local_haplo_tf0.01,
              cliquesnv_local_haplo_snv_tf0.01,
              viloca_alpha_0.000001,
              viloca_alpha_0.00001_K100,
              ]
replicate_count: 1
haplotype_generation: null
params_path: config_realdata/params.csv
master_seq_path: null
