method_list: [
              viloca_alpha_0.0001,
              viloca_alpha_0.00001,
              viloca_alpha_0.000001,
              viloca_alpha_0.0000001,
              viloca_envp,
              #viloca_multi, for those two I had problems with the core allocation on the cluster
              #viloca_envp_multi,
              viloca_learn_error_params
              ]
replicate_count: 5
haplotype_generation: distance
params_path: config_varyvilocaparams/params.csv
master_seq_path: ../../../../hiv/HXB2.fasta
